name: Generate PSI report
on:
  schedule:
  - cron: "30 2 * * 6"

jobs:
  run_psi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
         persist-credentials: false
         fetch-depth: 0

      - name: psi-gh-action
        uses: mazipan/psi-gh-action@1.3.0
        with:
          api_key: ${{ secrets.PSI_API_KEY }}
          urls: |
            https://mazipan.space/
          devices: |
            mobile
            desktop
          runs: 1
          branch: master
          push_back: true
          token: ${{ secrets.GITHUB_TOKEN }}
