# name: Deploy

# on:
#   push:
#     branches:
#       - master
#   #schedule:
#   #  - cron: "0 0 1 * *"

# jobs:
#   deploy:

#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
#         with:
#          persist-credentials: false
#          fetch-depth: 0
#          submodules: true

#       - name: Use node 12
#         uses: actions/setup-node@v1
#         with:
#           node-version: 12.x

#       - name: Get yarn cache
#         id: yarn-cache
#         run: echo "::set-output name=dir::$(yarn cache dir)"

#       - name: Cache Node.js modules
#         uses: actions/cache@v1
#         with:
#           path: ${{ steps.yarn-cache.outputs.dir }}
#           key: ${{ runner.OS }}-yarn-${{ hashFiles('**/yarn.lock') }}
#           restore-keys: |
#             ${{ runner.OS }}-yarn-

#       - name: Gatsby Cache Folder
#         uses: actions/cache@v1
#         id: gatsby-cache-folder
#         with:
#           path: .cache
#           key: ${{ runner.os }}-cache-gatsby
#           restore-keys: |
#             ${{ runner.os }}-cache-gatsby

#       - name: Gatsby Public Folder
#         uses: actions/cache@v1
#         id: gatsby-public-folder
#         with:
#           path: public/
#           key: ${{ runner.os }}-public-gatsby
#           restore-keys: |
#             ${{ runner.os }}-public-gatsby

#       - name: Install dependencies
#         run: yarn install --pure-lockfile

#       - name: Build project
#         run: yarn build:ci
#         env:
#           ADS_CLIENT: ${{ secrets.ADS_CLIENT }}
#           API_LIKE_BUTTON: ${{ secrets.API_LIKE_BUTTON }}
#           FULL_DOMAIN: ${{ secrets.FULL_DOMAIN }}
#           GA_KEY: ${{ secrets.GA_KEY }}
#           LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
#           SITE_NAME: ${{ secrets.SITE_NAME }}
#           SITE_VERIFICATION: ${{ secrets.SITE_VERIFICATION }}

#       - name: GitHub Pages Deploy
#         uses: peaceiris/actions-gh-pages@v3
#         with:
#           personal_token: ${{ secrets.PERSONAL_TOKEN }}
#           publish_dir: ./public
